### ISSUE TITLE
Feature: GraphQL Client Setup

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/generator-jm-vuejs#1]
### Tasks

- [x] Check templates for importing all components and files.
- [x] Setup basic VueJS configuration for GraphQL Client
- [x] Integrate GraphQL Client with the client.conf.json workflow
