### ISSUE TITLE
Feature: HTTP Client Setup

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/generator-jm-vuejs#2]
### Tasks

- [x] Check templates for importing all components and files.
- [x] Setup basic VueJS configuration for HTTP Client
- [x] Integrate HTTP Client with the client.conf.json workflow
