### ISSUE TITLE
Feature: Add GraphQL & VUEX functionality via vue-supply.

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/generator-jm-vuejs#7]
### Tasks

- [ ] Add [vue-supply](https://github.com/Akryum/vue-supply) to the mix.
- [ ] Check templates for importing all components and files.
- [ ] Make sure to integrate vue-supply properly with both vue-apollo and vuex.
